# Generated by Django 4.0.4 on 2022-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
