# Generated by Django 4.0.4 on 2022-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_user',
            field=models.BooleanField(default=False),
        ),
    ]
