# Generated by Django 4.0.4 on 2022-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_basic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='subscription_type',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('PREMIUM', 'PREMIUM')], default='BASIC', max_length=10),
            preserve_default=False,
        ),
    ]
