# Generated by Django 4.0.4 on 2022-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subcription_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(default='nil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='nil', max_length=100),
            preserve_default=False,
        ),
    ]
