# Generated by Django 4.0.4 on 2022-04-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_session_description_session_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='session',
        ),
    ]
