# Generated by Django 4.0.4 on 2022-05-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_roles_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_IT_support',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_accountant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_community_manager',
        ),
    ]
