# Generated by Django 4.0.4 on 2022-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_is_it_support_remove_user_is_accountant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_IT_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_community_manager',
            field=models.BooleanField(default=False),
        ),
    ]
